services:
  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: "AKIAIT2Z5TDYPX3ARJBA"
      MINIO_SECRET_KEY: "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"
    command: "server /data"
    ports:
      - "8124:9000"
      - "8125:9001"