name: "pulpcore.CI"

services:
  pulp:
    build:
      context: ../..
      dockerfile: ".ci/compose/Containerfile"
      args:
        - EXTRA_INSTALL=${EXTRA_INSTALL}
        - PACKAGE_SRC=${PACKAGE_SRC}
        - CORE_CLIENT_SRC=${CORE_CLIENT_SRC}
        - FILE_CLIENT_SRC=${FILE_CLIENT_SRC}
        - CERTGUARD_CLIENT_SRC=${CERTGUARD_CLIENT_SRC}
        - FULL_INSTALL=${FULL_INSTALL}
        - TEST=${TEST}
    image: "localhost/pulp-ci:${COMPOSE_PROJECT_NAME}"
    ports:
      - "5003:443"
    healthcheck:
      test: "curl -f http://localhost:24817${PULP_API_ROOT:-/pulp/}api/v3/status/"
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      PULP_WORKERS: "4"
      PULP_HTTPS: "true"
      PULP_CA_BUNDLE: "/etc/pulp/certs/pulp_webserver.crt"
