FROM pulp/pulp-ci-centos9:latest

ARG EXTRA_INSTALL
RUN if [ -n "$EXTRA_INSTALL" ]; then \
    dnf install -y $EXTRA_INSTALL; \
fi

RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install --upgrade pip setuptools wheel

# Build context is the root of the project
COPY pulpcore/tests/functional/assets/api_root_rewrite.conf /etc/nginx/pulp/api_root_rewrite.conf
COPY test_requirements.txt unittest_requirements.txt functest_requirements.txt /

ARG PACKAGE_SRC
COPY $PACKAGE_SRC /

# Now copy test runner specific files
ARG TEST CORE_CLIENT_SRC FILE_CLIENT_SRC CERTGUARD_CLIENT_SRC
COPY .ci/compose/$TEST/settings.py /etc/pulp/settings.py
COPY .ci/compose/$TEST/constraints.txt /constraints.txt
COPY $CORE_CLIENT_SRC $FILE_CLIENT_SRC $CERTGUARD_CLIENT_SRC /

# Now install everything
ARG FULL_INSTALL
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install $FULL_INSTALL


USER pulp:pulp
RUN PULP_STATIC_ROOT=/var/lib/operator/static/ PULP_CONTENT_ORIGIN=localhost \
       /usr/local/bin/pulpcore-manager collectstatic --clear --noinput --link
# Needed for tests
RUN echo 'machine pulp login admin password password' > ~pulp/.netrc
USER root:root
RUN echo '%wheel        ALL=(ALL)       NOPASSWD: ALL' > /etc/sudoers.d/nopasswd && \
    mkdir /.pytest_cache && \
    usermod -a -G wheel pulp && \
    chmod 600 ~pulp/.netrc
    # cat /etc/pulp/certs/pulp_webserver.crt >> $(python3 -c 'import certifi; print(certifi.where())')
