#!/bin/bash

# This script expects all <app_label>-api.json files to exist in the plugins .ci/compose/<test>/ directory
# It produces a client file in the plugins .ci/compose/<test>/ directory.

# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by it. Please use
# './plugin-template --github pulpcore' to update this file.
#
# For more info visit https://github.com/pulp/plugin_template

set -mxeuo pipefail

# make sure this script runs at the repo root
cd "$(dirname "$(realpath -e "$0")")"/../../..

TEST=$1
TEST_DIR="$(realpath ".ci/compose/${TEST}")"
TYPE=${2:-python}
GENERATOR_DIR=${3:-../pulp-openapi-generator}

pushd ${GENERATOR_DIR}
# rm -rf "pulpcore-client"

./gen-client.sh "${TEST_DIR}/core-api.json" "core" ${TYPE} "pulpcore"

pushd pulpcore-client
if [ "$TYPE" = "python" ]; then
    python -m build
    twine check dist/*
    cp dist/* "${TEST_DIR}/"
elif [ "$TYPE" = "ruby" ]; then
    gem build pulpcore_client
    cp "./pulpcore_client-"*".gem" "${TEST_DIR}/"
else
    echo "Invalid type: $TYPE"
    exit 1
fi
popd
# # rm -rf "pulp_file-client"

# ./gen-client.sh "${TEST_DIR}/file-api.json" "file" ${TYPE} "pulp_file"

# pushd pulp_file-client
# if [ "$TYPE" = "python" ]; then
#     python -m build
#     twine check dist/*
#     cp dist/* "${TEST_DIR}/"
# else if [ "$TYPE" = "ruby" ]; then
#     gem build pulp_file_client
#     cp "./pulp_file_client-"*".gem" "${TEST_DIR}/"
# else
#     echo "Invalid type: $TYPE"
#     exit 1
# popd
# # rm -rf "pulp_certguard-client"

# ./gen-client.sh "${TEST_DIR}/certguard-api.json" "certguard" ${TYPE} "pulp_certguard"

# pushd pulp_certguard-client
# if [ "$TYPE" = "python" ]; then
#     python -m build
#     twine check dist/*
#     cp dist/* "${TEST_DIR}/"
# else if [ "$TYPE" = "ruby" ]; then
#     gem build pulp_certguard_client
#     cp "./pulp_certguard_client-"*".gem" "${TEST_DIR}/"
# else
#     echo "Invalid type: $TYPE"
#     exit 1
# fi
# popd

popd
