#!/usr/bin/env bash

# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by it. Please use
# './plugin-template --github pulpcore' to update this file.
#
# For more info visit https://github.com/pulp/plugin_template

# make sure this script runs at the repo root
cd "$(dirname "$(realpath -e "$0")")"/../../..

set -mveuo pipefail

TEST=$1

# I removed all the switching base image logic from commit message.

export POST_SETUP=$PWD/.ci/compose/scripts/post_setup.sh

if [[ "$TEST" = "pulp" ]]; then
  python3 .ci/scripts/calc_constraints.py -u pyproject.toml > .ci/compose/$TEST/constraints.txt
fi
if [[ "$TEST" = "lowerbounds" ]]; then
  python3 .ci/scripts/calc_constraints.py pyproject.toml > .ci/compose/$TEST/constraints.txt
fi

if [ -f $POST_SETUP ]; then
  source $POST_SETUP
fi
