ALLOWED_EXPORT_PATHS =["/tmp"]
ALLOWED_IMPORT_PATHS = ["/tmp"]
CONTENT_PATH_PREFIX = "/somewhere/else/"
CSRF_TRUSTED_ORIGINS = ["https://pulp:443"]
ORPHAN_PROTECTION_TIME = 0
TASK_PROTECTION_TIME = 10
TMPFILE_PROTECTION_TIME = 10
UPLOAD_PROTECTION_TIME = 10